theme: jekyll-theme-cayman
title: UP42 Customer Support Challenge*
description: This is a page created for the challenge of Up42 and display an interactive map made with Folium. It a sample of the Bhutan forest.
logo: https://github.com/diegoalarc/Challenge_up42/blob/main/results/sentinel_2/quicklook_S2B_46RBR_20210106_0_L2A.jpg```
